# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Deployment

on:
  pull_request:
  push:
    branches:
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Zig environment
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.12.0
      - name: Build the documentation
        run: zig build doc
      - name: Minify the documentation
        uses: docker://tdewolff/minify:latest
        with:
          args: -o zig-out/docs/ -r zig-out/docs/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: zig-out/docs
